server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://193.112.179.102/flower_shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mirage666666
    hikari:
      max-lifetime: 1800000
      connection-test-query: SELECT 1


jwt:
  secret: jason

file:
  upload-dir: C:/Users/Public/Desktop/




#logging:
#  level:
#    org.springframework.security: DEBUG
#    root: DEBUG