server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql:///evaluation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mirage666666

jwt:
  secret: jason



#logging:
#  level:
#    org.springframework.security: DEBUG
#    root: DEBUG