server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://193.112.179.102/flower_shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mirage666666
    hikari:
      max-lifetime: 60
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  secret: jason


file:
  upload-dir: C:/my_project/flower-shop/flower_image/

baseImagePath: http://localhost:8081/mirageLedger/image/view/

pythonUrl: http://localhost:5000




#logging:
#  level:
#    org.springframework.security: DEBUG
#    root: DEBUG